project:
  type: book

book:
  title: "Machine Learning Safety Playbook"
  author: "Mateus Molina"
  repo-url: https://github.com/MateusMolina/ml-safety-playbook
  repo-actions: [edit]
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - introduction/intro-uncertainty.qmd
        - introduction/probability-distributions.qmd
        - introduction/example-anomaly-detection.qmd
        - introduction/example-spam-detection.qmd
    - references.qmd
    - part: "Concepts"
  appendices:
    - appendix/propositions-theorems.qmd
    - appendix/notation.qmd
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  echo: false

custom-amsthm:
  - key: prm
    name: Problem
  - key: chl
    name: Challenge

filters:
  - custom-amsthm-environments
  - pseudocode

resources:
  - CNAME
