project:
  type: book

book:
  title: "Machine Learning Safety Playbook"
  author: "Mateus Molina"
  repo-url: https://github.com/MateusMolina/ml-safety-playbook
  repo-actions: [edit]
  date: today
  chapters:
    - index.qmd
    - summary.qmd
    - part: "Introduction"
      chapters:
        - introduction/handling-uncertainty.qmd
    - references.qmd
    - part: "Concepts"
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

execute:
  echo: false
  freeze: auto

custom-amsthm:
  - key: prm
    name: Problem

filters:
  - custom-amsthm-environments
  - pseudocode

resources:
  - CNAME
